import 'dart:io';

import 'package:dart_acdc/dart_acdc.dart';
import 'package:dio/dio.dart';
import 'package:test/test.dart';

import '../helpers/mock_network_info.dart';
import '../helpers/pinning_test_server.dart';

void main() {
  group('Certificate Pinning Integration', () {
    late PinningTestServer server;
    // The SPKI from print output of generate_certs.sh
    // "SPKI SHA-256 Pin: SHA256:AgZnBoktUi/KWOA5ma+y6jW9+WtFMqZrSYtAwLQ9vW0="
    // Update this dynamically? Ideally we read it from the file.
    late String validPin;

    setUp(() async {
      // Read the pin generated by the script
      final pinFile = File('test/security/certs/pin.txt');
      if (!pinFile.existsSync()) {
        fail('Pin file not found. Run test/security/generate_certs.sh first.');
      }
      validPin = pinFile.readAsStringSync().trim();

      server = PinningTestServer();
      await server.start();
    });

    tearDown(() async {
      await server.stop();
    });

    test('valid pin allows connection to self-signed server', () async {
      final config = CertificatePinningConfig(
        allowedPins: {
          'localhost': [validPin],
        },
      );

      final dio = await const AcdcClientBuilder()
          .withBaseUrl(server.baseUrl)
          .withCertificatePinning(config)
          .withNetworkInfo(MockNetworkInfo())
          .disableAuth()
          .disableCache()
          .build();

      final response = await dio.get<Map<String, dynamic>>('/');
      expect(response.statusCode, 200);
      expect(response.data, {'data': 'secure_data'});
    });

    test('invalid pin aborts connection', () async {
      final config = CertificatePinningConfig(
        allowedPins: const {
          'localhost': ['SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='],
        },
      );

      final dio = await const AcdcClientBuilder()
          .withBaseUrl(server.baseUrl)
          .withCertificatePinning(config)
          .withNetworkInfo(MockNetworkInfo())
          .disableAuth()
          .disableCache()
          .build();

      try {
        await dio.get<dynamic>('/');
        fail('Should have thrown DioException');
      } on DioException catch (e) {
        // Depending on platform and Dio version, this might be wrapped differently.
        // Usually a HandshakeException inside DioException.
        // With pinning enabled, we expect AcdcSecurityException if our interceptor caught it,
        // OR a lower level connection error if the badCertificateCallback rejected it.
        // Since we are using IOHttpClientAdapter's validateCertificate/badCertificateCallback,
        // it fails at the handshake level.
        expect(e.type,
            anyOf(DioExceptionType.connectionError, DioExceptionType.unknown),);
        expect(e.error.toString(), contains('HandshakeException'));
      }
    });

    test('reportOnly mode allows connection despite mismatch', () async {
      var callbackInvoked = false;

      final config = CertificatePinningConfig(
          allowedPins: const {
            'localhost': [
              'SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
            ],
          },
          reportOnly: true,
          onPinningFailure: (host, certs) {
            callbackInvoked = true;
            expect(host, 'localhost');
            expect(certs, isNotEmpty);
          },);

      final dio = await const AcdcClientBuilder()
          .withBaseUrl(server.baseUrl)
          .withCertificatePinning(config)
          .withNetworkInfo(MockNetworkInfo())
          .disableAuth()
          .disableCache()
          .build();

      final response = await dio.get<Map<String, dynamic>>('/');
      expect(response.statusCode, 200);
      expect(callbackInvoked, isTrue,
          reason: 'Callback should be invoked in reportOnly mode',);
    });
  });
}
